### ISSUE TITLE
Define feeds to fetch in settings.json

### ISSUE THREAD

**Issue by xavxyz** [xavcz/nova-post-by-feed#2]
This can be handled, reusing the way some fields are disabled in the settings modal!

See PR: https://github.com/TelescopeJS/Telescope/pull/1321#issuecomment-217381673

Let's try! 👯

**Comment by Air2air** [comment]
Xavier est-il possible de mettre l'aliment dans une collection ?  You know why :).

pour chaque utilisateur qui peut créer un poste .

**Comment by xavxyz** [comment]
Yes it's a collection too 👍
Le sam. 20 août 2016 à 21:48, Todd Dunning notifications@github.com a
écrit :
