### ISSUE TITLE
youtube description is not copied to posts.description

### ISSUE THREAD

**Issue by newomatic** [xavcz/nova-post-by-feed#8]
If the RSS feed is from youtube. we need to use the media.description tag.

See example XML:

`https://www.youtube.com/feeds/videos.xml?channel_id=UCcvNYxWXR_5TjVK7cSCdW-g`

**Comment by xavxyz** [comment]
Right, thanks for raising this issue! I'm on it 👍

**Comment by abhaytalreja** [comment]
@xavcz - Thanks man! i actually tried to take the package and edit it, i was getting some Telescope reference errors. I had already fixed this in legacy though. Let me know if you need the code.

**Comment by xavxyz** [comment]
Yeah that would be awesome @abhaytalreja! It would be faster 🚀

**Comment by abhaytalreja** [comment]
```
if (item.description) {
          post.body = toMarkdown(he.decode(item.description));
          // a post body cannot exceed 3000 characters
          if (post.body.length > 3000)
            post.body = post.body.substring(0, 2999);
        }


// Copy the below if loop
if(post.body === undefined && item.link.indexOf('youtube') > 0) {
    post.body = toMarkdown(he.decode(item["media:group"]["media:description"]['#']));
}
```
