### ISSUE TITLE
TypeError: Router.path is not a function

### ISSUE THREAD

**Issue by sweetppro** [xavcz/nova-post-by-feed#9]
I am trying to implement your package, and get this error:
`TypeError: Router.path is not a function`
when trying to run Nova?

it happens on these lines(from your demo code):
`<MenuItem className="dropdown-item" eventKey="1" href={Router.path("users.single", {slug: user.telescope.slug})}>Profile</MenuItem>
            <MenuItem className="dropdown-item" eventKey="2" href={Router.path("account")}>Edit Account</MenuItem>`

am I missing something obvious here?
Ive already imported `Router` from `react-router`

**Comment by xavxyz** [comment]
Hey @sweetppro! Thanks for the heads up, the doc is outdated and not compatible with the current Nova.

This part of the component should look like what's in `UsersMenu` now: https://github.com/TelescopeJS/Telescope/blob/master/packages/nova-base-components/lib/users/UsersMenu.jsx#L23-L31

PR welcomed if you want to update the README :)

**Comment by sweetppro** [comment]
here is my updated code which does work, but may not be the best:
https://gist.github.com/sweetppro/c2ed00782b7adb03dce973a7365d65db

**Comment by xavxyz** [comment]
Thanks!
